### ISSUE TITLE
Why Some Pages Accessible Via URL But Not Nav?

### ISSUE THREAD

**Issue by wesleyboar** [DesignSafe-CI/DS-User-Guide#13]
## Question

Why can several pages load via URL, but do not show up in nav sidebar?

## Actual Result

| URL | Nav (Top) | Nav (Bottom) |
| - | - | - |
| https://www.designsafe-ci.org/user-guide/usecases/arduino/usecase/ | <img width="960" alt="ardunio top" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/6e36eb5f-a11e-4966-b9e6-74ecbf505492"> | <img width="960" alt="arduino bottom" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/82a74f99-e991-48f7-b0cd-2dc272034217"> |
| https://www.designsafe-ci.org/user-guide/usecases/dawson/usecase/ | <img width="960" alt="dawson top" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/46ce67a9-bb56-4ec2-9144-5ffcde033c82"> | <img width="960" alt="dawson bottom" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/2f62fe04-c17d-4092-a00a-0d4e21ae9a01"> 
| https://www.designsafe-ci.org/user-guide/dictionary/experimental/ | <img width="960" alt="dict top" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/e5f46780-c7a9-4228-b3d6-e8beedb5f046"> | <img width="960" alt="dict bottom" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/c47c4184-ace7-4e4a-a133-fecc2d5d76a5"> |

## Expected Result

| URL | Nav (Active) |
| - | - |
| https://www.designsafe-ci.org/user-guide/usecases/windstormsurgeusecases/ | <img width="960" alt="wind" src="https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/08df8b9a-4258-4cac-940d-5b7e106343db"> |

**Comment by wesleyboar** [comment]
I asked around, and got the following answers:

- It is intentional, because we did not want too much to show in the navigation.
- The materials are very deeply nested, so navigation can get deep quickly.
- Reorganization made nav "flatter", but nav could still get "too long".
    <sup>We have some very long docs, because they had been individual docs.</sup>
- Some files may exist only as "a backup" not meant to be shown in nav.
- There was a lot of duplication in the documentation.

I think there is a way to:
- show everything (except duplicates)
- limit navigation depth
- offer ways to navigate docs deeper than the nav shows

Super long docs may still be a problem. It is a problem on https://docs.tacc.utexas.edu also. I propose revisiting after redesign (#1).

**Comment by silviamazzoni** [comment]
I resolved the first one with Pedro's. he hadn't put in the title # OpenSees Model Calibration, which is what the nav page referred to.

**Comment by silviamazzoni** [comment]
the page that collates them does two things, 1. collates them, 2 adds the bookmarks to the nav bar. but the bookmark that it was using wasn't found in the collated page

**Comment by wesleyboar** [comment]
As an issue written and labeled as a question, I think we've both answered this (above), so I'll close it.

**Answer Summary**: A mix of navigation usage[^1], navigation gotchas[^1], duplicate docs[^2], and either neglect or lack of authority to resolve. I've gotten approval to work with contributors and designer to resolve this, so expect progress.

[^1]: Both @silviamazzoni and @wesleyboar are aware of navigation usage and gotchas and what are options are.

**Comment by wesleyboar** [comment]
[New instances of the problem were recently introduced.](https://github.com/DesignSafe-CI/DS-User-Guide/pull/35#pullrequestreview-2103251861.)
